app-name = "chattrix-backend"
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:20"

[[services]]
protocol = "tcp"
internal_port = 3001
processes = ["app"]

  [services.http_checks.checks.status]
    success_codes = [200, 206, 401, 403, 404]
    interval = "30s"
    timeout = "5s"

[env]
  PORT = "3001"
  NODE_ENV = "production"

[checks]
  [checks.tcp_checks.chattrix_check]
    grace_period = "5s"
    interval = "30s"
    timeout = "5s"
